### ISSUE TITLE
Support Java 16

### ISSUE THREAD

**Issue by gunnarmorling** [kbastani/order-delivery-microservice-example#3]
Java 16 is the current stable version, but the build fails due to some access restriction around Lombok (I suppose caused by the fact that --illegal-access=deny is the default starting with 16. A version update of Lombok might suffice potentially.

**Comment by kbastani** [comment]
You're all set.

**Comment by gunnarmorling** [comment]
Oh, very nice, completely missed you had done this. Thx!
