### ISSUE TITLE
Clarify structure of order_event table

### ISSUE THREAD

**Issue by gunnarmorling** [kbastani/order-delivery-microservice-example#5]
Hey @kbastani, there's still quite a few fields in `order_event`, which I don't think we need, like restaurant_city, order_location_lat, etc. Or do we need them? The structure currently looks a bit like a mixture of an outbox table (essentially solely an event container) and an actual table for storing purchase orders with all the distinct columns, which is a bit confusing.

Slightly related: can we make last_modified an actual temporal column type like TIMESTAMP?

**Comment by kbastani** [comment]
We do need all of those fields. These are dimensions used by Pinot for analytical dashboards.

> Slightly related: can we make last_modified an actual temporal column type like TIMESTAMP?

Sure, I don't think that will be an issue. As long as what gets loaded into Pinot is a `LONG` data type. I'll make that change now.

**Comment by gunnarmorling** [comment]
> We do need all of those fields. These are dimensions used by Pinot for analytical dashboards.

Ok, but they exist twice, once as actual columns within the table, and once within the `order_payload` JSON structure. Only the latter is what's currently propagated via Debezium, as I was assuming that'd suffice?

**Comment by kbastani** [comment]
Ah, yes I see your point. From an API consumer perspective, it would be useful to have the REST API return a well-formed JSON response. The payload field is for Debezium, but the `/order/{id}/events` API returns back the collection of events. Let's leave it for now if that's okay. I think what might be needed here is to create a different event type for CDC that only contains the necessary fields for Debezium.

**Comment by kbastani** [comment]
Let's close this issue for timestamps, which is good to go... I'll create a new issue for cleaning up the outbox table's schema.
